blank_issues_enabled: false
contact_links:
  - name: OpenWrt Forum thread (general questions / discussion)
    url: https://forum.openwrt.org/t/doh-proxy-https-dns-proxy-new-rfc8484-supporting-package-and-web-ui/50832
    about: For usage questions and general discussion, please use the forum thread.
